#ifndef CONSTANTES_H_
#define CONSTANTES_H_

#define ERROR -1
#define OK 0
#define TAMANIO_BUFFER 32768
#define STRING_BUFFER 32768
#define BLOQUE_LLENO 1
#define BLOQUE_NO_LLENO 0
#define TIPO_CLAVE_NUMERICA 1
#define TAM_TOTAL_NODO 512
#define TAM_CONTROL_NODO 12
#define TAM_EFECTIVO_NODO (TAM_TOTAL_NODO - TAM_CONTROL_NODO)

#endif /* CONSTANTES_H_ */
